# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: input.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binput.proto\x12\x0c\x63loud_gaming\"\xb1\x03\n\x0bPlayerInput\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x04\x12;\n\x08keyboard\x18\n \x01(\x0b\x32\'.cloud_gaming.PlayerInput.KeyboardStateH\x00\x12\x35\n\x05mouse\x18\x0b \x01(\x0b\x32$.cloud_gaming.PlayerInput.MouseStateH\x00\x12\x39\n\x07gamepad\x18\x0c \x01(\x0b\x32&.cloud_gaming.PlayerInput.GamepadStateH\x00\x1a%\n\rKeyboardState\x12\x14\n\x0cpressed_keys\x18\x01 \x03(\r\x1aX\n\nMouseState\x12\x0f\n\x07\x64\x65lta_x\x18\x01 \x01(\x05\x12\x0f\n\x07\x64\x65lta_y\x18\x02 \x01(\x05\x12\x13\n\x0b\x62utton_mask\x18\x03 \x01(\r\x12\x13\n\x0bwheel_delta\x18\x04 \x01(\x05\x1a\x41\n\x0cGamepadState\x12\x12\n\ngamepad_id\x18\x01 \x01(\r\x12\x0c\n\x04\x61xes\x18\x02 \x03(\x02\x12\x0f\n\x07\x62uttons\x18\x03 \x03(\rB\x07\n\x05inputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERINPUT']._serialized_start=30
  _globals['_PLAYERINPUT']._serialized_end=463
  _globals['_PLAYERINPUT_KEYBOARDSTATE']._serialized_start=260
  _globals['_PLAYERINPUT_KEYBOARDSTATE']._serialized_end=297
  _globals['_PLAYERINPUT_MOUSESTATE']._serialized_start=299
  _globals['_PLAYERINPUT_MOUSESTATE']._serialized_end=387
  _globals['_PLAYERINPUT_GAMEPADSTATE']._serialized_start=389
  _globals['_PLAYERINPUT_GAMEPADSTATE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
